google_sheet_name: "Norifarm shipments"
summary_sheet_name: "Weekly Summary"
openai_api_key: "xxxx"
credentials_path: "C:\\Users\\user\\OneDrive\\Desktop\\NoriFarm\\credentials\\credentials.json"
